//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantiyeYönetim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SantiyeEntities1 : DbContext
    {
        public SantiyeEntities1()
            : base("name=SantiyeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Attendance> Tbl_Attendance { get; set; }
        public virtual DbSet<Tbl_Employees> Tbl_Employees { get; set; }
        public virtual DbSet<Tbl_Equipment> Tbl_Equipment { get; set; }
        public virtual DbSet<Tbl_Materials> Tbl_Materials { get; set; }
        public virtual DbSet<Tbl_MaterialUsage> Tbl_MaterialUsage { get; set; }
        public virtual DbSet<Tbl_ProjectAssignments> Tbl_ProjectAssignments { get; set; }
        public virtual DbSet<Tbl_Projects> Tbl_Projects { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
