//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantiyeYönetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MaterialUsage
    {
        public int UsageID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<decimal> QuantityUsed { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
    
        public virtual Tbl_Materials Tbl_Materials { get; set; }
        public virtual Tbl_Projects Tbl_Projects { get; set; }
    }
}
